[kamailio]
102.22.27.147 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/github_actions ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[freeswitch]
102.22.27.148 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/github_actions ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[jasmin]
102.22.27.150 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/github_actions ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[postgres]
102.22.27.149 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/github_actions ansible_ssh_common_args='-o StrictHostKeyChecking=no'
