- name: Install FreeSWITCH build dependencies
  apt:
    name:
      - git
      - wget
      - gnupg2
      - lsb-release
      - build-essential
      - pkg-config
      - libtool
      - autoconf
      - automake
      - libncurses5-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libpcre3-dev
      - libspeexdsp-dev
      - libsqlite3-dev
      - libedit-dev
      - libldns-dev
      - libopus-dev
      - libsndfile1-dev
      - liblua5.2-dev
    state: present
    # update_cache: yes

- name: Remove any old FreeSWITCH repo definitions
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/freeswitch.list
    state: absent

- name: Remove old FreeSWITCH key if present
  ansible.builtin.file:
    path: /usr/share/keyrings/freeswitch-archive-keyring.gpg
    state: absent

- name: Import FreeSWITCH GPG key
  ansible.builtin.get_url:
    url: https://files.freeswitch.org/repo/deb/freeswitch-1.10-bookworm/freeswitch-archive-keyring.gpg
    dest: /usr/share/keyrings/freeswitch-archive-keyring.gpg
    mode: '0644'

- name: Add authenticated FreeSWITCH repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/freeswitch-archive-keyring.gpg] https://{{ fs_username }}:{{ fs_password }}@files.freeswitch.org/repo/deb/freeswitch-1.10-bookworm/ bookworm main"
    state: present
    filename: freeswitch

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Clone FreeSWITCH source
  git:
    repo: https://github.com/signalwire/freeswitch.git
    dest: /usr/src/freeswitch
    version: v1.10.11

- name: Build and install FreeSWITCH
  shell: |
    cd /usr/src/freeswitch
    ./bootstrap.sh -j
    ./configure
    make -j$(nproc)
    make install
    make sounds-install moh-install
  args:
    creates: /usr/local/freeswitch/bin/freeswitch

# setup sip profile configuration file with Jinja2 templating to use variables from group_vars
- name: Deploy FreeSWITCH configuration
  template:
    src: vars/freeswitch_sip_profiles.xml.j2
    dest: /usr/local/freeswitch/conf/sip_profiles/sip_profiles.xml
    owner: root
    group: root
    mode: '0644'